### PR TITLE
Optimized MPI override

### PR DESCRIPTION
**Pull request by marcgamell**
* Implemented Fenix request store instead of hash table
* Improved build system and instructions

### CODE REVIEW

**Comment by rfvander** [comment]
I am trying to merge optimized with optimized_squashed and get this:
[rfvander@esgmonster Fenix]$ git branch --set-upstream-to=mgamell/optimized_squashed optimized_squashed                                                             
Branch optimized_squashed set up to track remote branch optimized_squashed from mgamell.
[rfvander@esgmonster Fenix]$ git pull
remote: Counting objects: 36, done. 
remote: Compressing objects: 100% (24/24), done. 
remote: Total 36 (delta 15), reused 33 (delta 12), pack-reused 0 
Unpacking objects: 100% (36/36), done.
From https://github.com/marcgamell/Fenix
   4aebd26..8f5a06c  optimized  -> mgamell/optimized
Auto-merging src/fenix_process_recovery.c
CONFLICT (content): Merge conflict in src/fenix_process_recovery.c
Auto-merging src/fenix_mpi_override.c
CONFLICT (content): Merge conflict in src/fenix_mpi_override.c
Removing src/fenix_hash.c
Removing src/fenix-config.h.in
Auto-merging include/fenix_comm_list.h
CONFLICT (modify/delete): cmake_scripts/run_cmake.sh deleted in 44229a3bb898069b93927347c9e7ff9367f1b312 and modified in HEAD. Version HEAD of cmake_scripts/run_cmake.sh left in tree.
Auto-merging README.md
CONFLICT (content): Merge conflict in README.md
Automatic merge failed; fix conflicts and then commit the result.
I can fix the README, but should I delete cmake_scripts/run_cmake.sh?

**Comment by marcgamell** [comment]
Merge should be conflict-free. I made sure of that.

Note that in your instructions you are trying to merge `marcgamell/optimized` with `marcgamell/optimized_squashed`. This is not the merging we are trying to do here.

You should first checkout `epizon-project/master`, and then try the `git pull`.

However, the easiest way to review my branch is:
```
git fetch mgamell optimized_squashed
git checkout mgamell/optimized_squashed
```

**Comment by rfvander** [comment]
OK, Marc, I started from scratch and got this. Must be something really stupid that I'm doing.
[rfvander@esgmonster Fenix]$ git clone https://github.com/epizon-project/Fenix.git                                                                                  
Cloning into 'Fenix'...
remote: Counting objects: 1607, done. 
remote: Compressing objects: 100% (6/6), done. 
remote: Total 1607 (delta 1), reused 2 (delta 0), pack-reused 1601 
Receiving objects: 100% (1607/1607), 2.07 MiB | 0 bytes/s, done.
Resolving deltas: 100% (1082/1082), done.
Checking connectivity... done.
[rfvander@esgmonster Fenix]$ cd Fenix/
[rfvander@esgmonster Fenix]$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
[rfvander@esgmonster Fenix]$ git fetch mgamell optimized_squashed                                                                                                   
fatal: 'mgamell' does not appear to be a git repository
fatal: Could not read from remote repository.
 
Please make sure you have the correct access rights
and the repository exists.

**Comment by marcgamell** [comment]
You need to add the remote before `git fetch`. Use this:

```
git remote add mgamell https://github.com/marcgamell/Fenix.git
```

**Comment by rfvander** [comment]
Ah, yes, thanks.

**Comment by rfvander** [comment]
Wait, I may have specified an incorrect path to the new library; testing again.

**Comment by rfvander** [comment]
I think we are ready for the merge

**Comment by rfvander** [comment]
We still need to copy fenix.h from the source directory to the install directory.

**Pull request merged**
